/*
 * gauge_face_speed.h -- LVGL image descriptor for the Firebird MPH
 * gauge face. 480x480 RGB565 true-color (no alpha), Pontiac-style
 * speedo with 0..120 MPH dial.  Raw pixel data lives in
 * gauge_face_speed.c, auto-generated by png_to_lvgl_c.py from
 * pontiac_speed_face_final.png.
 *
 * Like the WATER TEMP face, this does NOT bake in a needle, pivot
 * hub, or digital readout -- those are LVGL widgets drawn on top so
 * they track the live ground speed from GPS.  The baked red 100..120
 * band is aesthetic; we don't trigger an alarm on it (overspeed isn't
 * a sensor fault).
 */
#ifndef GAUGE_FACE_SPEED_H
#define GAUGE_FACE_SPEED_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern const lv_img_dsc_t gauge_face_speed;

#ifdef __cplusplus
}
#endif

#endif /* GAUGE_FACE_SPEED_H */
